In [28]:
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv('customer_segmentation.csv')

In [4]:
df.head()

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response
0,5524,1957,Graduation,Single,58138.0,0,0,04-09-2012,58,635,...,7,0,0,0,0,0,0,3,11,1
1,2174,1954,Graduation,Single,46344.0,1,1,08-03-2014,38,11,...,5,0,0,0,0,0,0,3,11,0
2,4141,1965,Graduation,Together,71613.0,0,0,21-08-2013,26,426,...,4,0,0,0,0,0,0,3,11,0
3,6182,1984,Graduation,Together,26646.0,1,0,10-02-2014,26,11,...,6,0,0,0,0,0,0,3,11,0
4,5324,1981,PhD,Married,58293.0,1,0,19-01-2014,94,173,...,5,0,0,0,0,0,0,3,11,0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2240 entries, 0 to 2239
Data columns (total 29 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   2240 non-null   int64
 1   Year_Birth           2240 non-null   int64
 2   Education            2240 non-null   object
 3   Marital_Status       2240 non-null   object
 4   Income               2216 non-null   float64
 5   Kidhome              2240 non-null   int64
 6   Teenhome             2240 non-null   int64
 7   Dt_Customer          2240 non-null   object
 8   Recency              2240 non-null   int64
 9   MntWines             2240 non-null   int64
 10  MntFruits            2240 non-null   int64
 11  MntMeatProducts      2240 non-null   int64
 12  MntFishProducts      2240 non-null   int64
 13  MntSweetProducts     2240 non-null   int64
 14  MntGoldProds         2240 non-null   int64
 15  NumDealsPurchases    2240 non-null   int64
 16  NumWebPurchases      2240 non-null   int64
 17  NumCatalogPurchases  2240 non-null   int64
 18  NumStorePurchases    2240 non-null   int64
 19  NumWebVisitsMonth    2240 non-null   int64
 20  AcceptedCmp3         2240 non-null   int64
 21  AcceptedCmp4         2240 non-null   int64
 22  AcceptedCmp5         2240 non-null   int64
 23  AcceptedCmp1         2240 non-null   int64
 24  AcceptedCmp2         2240 non-null   int64
 25  Complain             2240 non-null   int64
 26  Z_CostContact        2240 non-null   int64
 27  Z_Revenue            2240 non-null   int64
 28  Response             2240 non-null   int64
dtypes: float64(1), int64(25), object(3)
memory usage: 507.6+ KB

In [6]:
df.drop('ID',axis=1)

,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,MntFruits,...,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response
0,1957,Graduation,Single,58138.0,0,0,04-09-2012,58,635,88,...,7,0,0,0,0,0,0,3,11,1
1,1954,Graduation,Single,46344.0,1,1,08-03-2014,38,11,1,...,5,0,0,0,0,0,0,3,11,0
2,1965,Graduation,Together,71613.0,0,0,21-08-2013,26,426,49,...,4,0,0,0,0,0,0,3,11,0
3,1984,Graduation,Together,26646.0,1,0,10-02-2014,26,11,4,...,6,0,0,0,0,0,0,3,11,0
4,1981,PhD,Married,58293.0,1,0,19-01-2014,94,173,43,...,5,0,0,0,0,0,0,3,11,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2235,1967,Graduation,Married,61223.0,0,1,13-06-2013,46,709,43,...,5,0,0,0,0,0,0,3,11,0
2236,1946,PhD,Together,64014.0,2,1,10-06-2014,56,406,0,...,7,0,0,0,1,0,0,3,11,0
2237,1981,Graduation,Divorced,56981.0,0,0,25-01-2014,91,908,48,...,6,0,1,0,0,0,0,3,11,0
2238,1956,Master,Together,69245.0,0,1,24-01-2014,8,428,30,...,3,0,0,0,0,0,0,3,11,0
2239,1954,PhD,Married,52869.0,1,1,15-10-2012,40,84,3,...,7,0,0,0,0,0,0,3,11,1

In [7]:
df['Education'].unique()

array(['Graduation', 'PhD', 'Master', 'Basic', '2n Cycle'], dtype=object)

In [8]:
df['Education'] = df['Education'].replace({'2n Cycle':'Diploma'})

In [9]:
df['Education'].unique()

array(['Graduation', 'PhD', 'Master', 'Basic', 'Diploma'], dtype=object)

In [10]:
df = pd.get_dummies(df,columns=['Education'])

In [11]:
df

,ID,Year_Birth,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,MntFruits,...,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response,Education_Basic,Education_Diploma,Education_Graduation,Education_Master,Education_PhD
0,5524,1957,Single,58138.0,0,0,04-09-2012,58,635,88,...,0,0,3,11,1,False,False,True,False,False
1,2174,1954,Single,46344.0,1,1,08-03-2014,38,11,1,...,0,0,3,11,0,False,False,True,False,False
2,4141,1965,Together,71613.0,0,0,21-08-2013,26,426,49,...,0,0,3,11,0,False,False,True,False,False
3,6182,1984,Together,26646.0,1,0,10-02-2014,26,11,4,...,0,0,3,11,0,False,False,True,False,False
4,5324,1981,Married,58293.0,1,0,19-01-2014,94,173,43,...,0,0,3,11,0,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2235,10870,1967,Married,61223.0,0,1,13-06-2013,46,709,43,...,0,0,3,11,0,False,False,True,False,False
2236,4001,1946,Together,64014.0,2,1,10-06-2014,56,406,0,...,0,0,3,11,0,False,False,False,False,True
2237,7270,1981,Divorced,56981.0,0,0,25-01-2014,91,908,48,...,0,0,3,11,0,False,False,True,False,False
2238,8235,1956,Together,69245.0,0,1,24-01-2014,8,428,30,...,0,0,3,11,0,False,False,False,True,False
2239,9405,1954,Married,52869.0,1,1,15-10-2012,40,84,3,...,0,0,3,11,1,False,False,False,False,True

In [29]:
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

In [13]:
df['Marital_Status'].unique()

array(['Single', 'Together', 'Married', 'Divorced', 'Widow', 'Alone',
       'Absurd', 'YOLO'], dtype=object)

In [14]:
df['Marital_Status'] = df['Marital_Status'].replace({
    'Alone': 'Single',
    'YOLO': 'Single',
    'Absurd': 'Single'
})

In [15]:
df = pd.get_dummies(df, columns=['Marital_Status'])

In [16]:
df['Dt_Customer'] = pd.to_datetime(df['Dt_Customer'],dayfirst = True)

In [17]:
df['Dt_Customer'] = (pd.to_datetime('today') - df['Dt_Customer']).dt.days

In [18]:
df['Dt_Customer'].unique()

array([4945, 4395, 4594, 4421, 4443, 4575, 4875, 4699, 4670, 4390, 4508,
       4909, 4864, 4834, 4949, 4740, 4885, 4972, 4821, 4835, 4451, 4750,
       4825, 4680, 4776, 4676, 4501, 4320, 4696, 4890, 4586, 4462, 4582,
       4420, 4795, 4708, 4756, 4518, 4552, 4283, 4879, 4683, 4461, 4880,
       4330, 4969, 4304, 4664, 4869, 4735, 4344, 4659, 4400, 4642, 4942,
       4778, 4665, 4487, 4686, 4331, 4384, 4557, 4729, 4938, 4935, 4751,
       4732, 4342, 4839, 4953, 4907, 4580, 4951, 4653, 4643, 4406, 4604,
       4630, 4314, 4441, 4315, 4500, 4380, 4318, 4866, 4726, 4492, 4656,
       4623, 4373, 4717, 4690, 4334, 4483, 4560, 4794, 4851, 4521, 4878,
       4286, 4846, 4574, 4438, 4777, 4635, 4509, 4407, 4715, 4716, 4303,
       4332, 4554, 4758, 4601, 4639, 4323, 4618, 4900, 4718, 4587, 4749,
       4901, 4891, 4958, 4290, 4348, 4396, 4844, 4910, 4638, 4572, 4537,
       4595, 4645, 4883, 4457, 4706, 4402, 4510, 4505, 4351, 4633, 4432,
       4368, 4937, 4842, 4319, 4287, 4556, 4440, 4296, 4853, 4613, 4773,
       4940, 4558, 4677, 4464, 4329, 4565, 4810, 4372, 4282, 4484, 4540,
       4886, 4629, 4485, 4694, 4939, 4737, 4385, 4914, 4806, 4703, 4371,
       4584, 4874, 4361, 4358, 4822, 4941, 4742, 4894, 4849, 4415, 4748,
       4692, 4356, 4745, 4489, 4550, 4467, 4325, 4526, 4615, 4495, 4963,
       4306, 4687, 4818, 4568, 4527, 4927, 4906, 4903, 4897, 4672, 4685,
       4294, 4865, 4793, 4754, 4285, 4904, 4657, 4383, 4427, 4366, 4790,
       4785, 4355, 4634, 4798, 4819, 4663, 4466, 4888, 4447, 4957, 4761,
       4814, 4815, 4386, 4542, 4359, 4931, 4398, 4710, 4444, 4673, 4476,
       4392, 4617, 4966, 4592, 4422, 4789, 4816, 4641, 4644, 4516, 4698,
       4783, 4721, 4573, 4734, 4817, 4646, 4852, 4876, 4765, 4970, 4486,
       4600, 4513, 4295, 4833, 4459, 4892, 4836, 4494, 4546, 4921, 4381,
       4830, 4959, 4752, 4871, 4857, 4350, 4877, 4654, 4962, 4828, 4662,
       4538, 4950, 4338, 4719, 4548, 4934, 4922, 4757, 4532, 4302, 4312,
       4902, 4738, 4804, 4503, 4417, 4774, 4763, 4336, 4724, 4367, 4712,
       4498, 4429, 4655, 4472, 4577, 4593, 4473, 4609, 4545, 4667, 4471,
       4705, 4780, 4960, 4736, 4317, 4924, 4562, 4434, 4714, 4397, 4965,
       4741, 4544, 4976, 4324, 4333, 4896, 4463, 4961, 4524, 4650, 4436,
       4925, 4855, 4496, 4974, 4829, 4956, 4881, 4491, 4627, 4682, 4534,
       4723, 4435, 4599, 4919, 4854, 4968, 4520, 4781, 4566, 4293, 4713,
       4416, 4607, 4470, 4860, 4608, 4455, 4490, 4374, 4364, 4424, 4517,
       4767, 4612, 4660, 4651, 4571, 4614, 4796, 4637, 4722, 4369, 4354,
       4926, 4570, 4893, 4535, 4775, 4567, 4801, 4335, 4596, 4628, 4847,
       4620, 4701, 4632, 4393, 4465, 4807, 4928, 4943, 4840, 4504, 4298,
       4700, 4597, 4480, 4414, 4977, 4458, 4533, 4468, 4826, 4691, 4559,
       4515, 4477, 4889, 4460, 4536, 4621, 4530, 4474, 4326, 4915, 4590,
       4678, 4377, 4363, 4391, 4343, 4284, 4727, 4502, 4898, 4693, 4979,
       4437, 4543, 4973, 4739, 4308, 4971, 4762, 4695, 4394, 4569, 4433,
       4551, 4768, 4340, 4787, 4753, 4697, 4944, 4583, 4681, 4481, 4850,
       4585, 4475, 4658, 4313, 4812, 4525, 4766, 4479, 4808, 4731, 4519,
       4746, 4311, 4792, 4702, 4782, 4382, 4610, 4859, 4619, 4449, 4920,
       4531, 4882, 4316, 4399, 4456, 4300, 4292, 4862, 4482, 4448, 4439,
       4744, 4647, 4802, 4506, 4689, 4720, 4803, 4606, 4666, 4626, 4679,
       4764, 4918, 4786, 4905, 4428, 4289, 4529, 4413, 4514, 4602, 4955,
       4353, 4365, 4824, 4884, 4805, 4405, 4349, 4616, 4541, 4861, 4341,
       4858, 4598, 4823, 4339, 4346, 4309, 4528, 4379, 4771, 4564, 4811,
       4469, 4870, 4975, 4704, 4511, 4640, 4625, 4899, 4684, 4954, 4450,
       4418, 4404, 4352, 4648, 4709, 4747, 4588, 4981, 4488, 4788, 4867,
       4770, 4929, 4668, 4579, 4360, 4652, 4412, 4831, 4887, 4624, 4431,
       4589, 4553, 4301, 4430, 4946, 4923, 4980, 4856, 4337, 4913, 4401,
       4327, 4848, 4967, 4408, 4387, 4563, 4895, 4539, 4779, 4952, 4419,
       4423, 4948, 4872, 4784, 4978, 4964, 4863, 4345, 4707, 4868, 4297,
       4375, 4760, 4947, 4357, 4347, 4649, 4675, 4549, 4409, 4725, 4561,
       4622, 4288, 4452, 4743, 4445, 4307, 4378, 4827, 4930, 4769, 4917,
       4728, 4370, 4820, 4497, 4611, 4841, 4305, 4688, 4603, 4478, 4912,
       4578, 4631, 4800, 4426, 4832, 4425, 4813, 4291, 4591, 4403, 4730,
       4362, 4299, 4493, 4759, 4376, 4843, 4932, 4674, 4837, 4522, 4605,
       4908, 4838, 4453])

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2240 entries, 0 to 2239
Data columns (total 37 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   ID                       2240 non-null   int64
 1   Year_Birth               2240 non-null   int64
 2   Income                   2216 non-null   float64
 3   Kidhome                  2240 non-null   int64
 4   Teenhome                 2240 non-null   int64
 5   Dt_Customer              2240 non-null   int64
 6   Recency                  2240 non-null   int64
 7   MntWines                 2240 non-null   int64
 8   MntFruits                2240 non-null   int64
 9   MntMeatProducts          2240 non-null   int64
 10  MntFishProducts          2240 non-null   int64
 11  MntSweetProducts         2240 non-null   int64
 12  MntGoldProds             2240 non-null   int64
 13  NumDealsPurchases        2240 non-null   int64
 14  NumWebPurchases          2240 non-null   int64
 15  NumCatalogPurchases      2240 non-null   int64
 16  NumStorePurchases        2240 non-null   int64
 17  NumWebVisitsMonth        2240 non-null   int64
 18  AcceptedCmp3             2240 non-null   int64
 19  AcceptedCmp4             2240 non-null   int64
 20  AcceptedCmp5             2240 non-null   int64
 21  AcceptedCmp1             2240 non-null   int64
 22  AcceptedCmp2             2240 non-null   int64
 23  Complain                 2240 non-null   int64
 24  Z_CostContact            2240 non-null   int64
 25  Z_Revenue                2240 non-null   int64
 26  Response                 2240 non-null   int64
 27  Education_Basic          2240 non-null   bool
 28  Education_Diploma        2240 non-null   bool
 29  Education_Graduation     2240 non-null   bool
 30  Education_Master         2240 non-null   bool
 31  Education_PhD            2240 non-null   bool
 32  Marital_Status_Divorced  2240 non-null   bool
 33  Marital_Status_Married   2240 non-null   bool
 34  Marital_Status_Single    2240 non-null   bool
 35  Marital_Status_Together  2240 non-null   bool
 36  Marital_Status_Widow     2240 non-null   bool
dtypes: bool(10), float64(1), int64(26)
memory usage: 494.5 KB

In [20]:
corr = df.corr()['Marital_Status_Widow']

In [21]:
corr

ID                         0.021937
Year_Birth                -0.161370
Income                     0.031706
Kidhome                   -0.073760
Teenhome                   0.045093
Dt_Customer                0.011679
Recency                    0.000218
MntWines                   0.036632
MntFruits                  0.032211
MntMeatProducts            0.018675
MntFishProducts            0.047894
MntSweetProducts           0.054631
MntGoldProds               0.046103
NumDealsPurchases          0.001237
NumWebPurchases            0.036576
NumCatalogPurchases        0.042780
NumStorePurchases          0.036305
NumWebVisitsMonth         -0.033705
AcceptedCmp3              -0.015123
AcceptedCmp4               0.039734
AcceptedCmp5               0.022610
AcceptedCmp1               0.000500
AcceptedCmp2              -0.000666
Complain                  -0.018355
Z_CostContact                   NaN
Z_Revenue                       NaN
Response                   0.051723
Education_Basic           -0.013679
Education_Diploma         -0.016884
Education_Graduation      -0.018332
Education_Master          -0.004743
Education_PhD              0.043360
Marital_Status_Divorced   -0.064133
Marital_Status_Married    -0.149508
Marital_Status_Single     -0.099447
Marital_Status_Together   -0.111526
Marital_Status_Widow       1.000000
Name: Marital_Status_Widow, dtype: float64

In [22]:
cols = corr[corr > 0.04].index

In [23]:
new_df = df[cols]

In [24]:
new_df = new_df.drop('Marital_Status_Widow',axis=1)

In [25]:
new_df

,Teenhome,MntFishProducts,MntSweetProducts,MntGoldProds,NumCatalogPurchases,Response,Education_PhD
0,0,172,88,88,10,1,False
1,1,2,1,6,1,0,False
2,0,111,21,42,2,0,False
3,0,10,3,5,0,0,False
4,0,46,27,15,3,0,True
...,...,...,...,...,...,...,...
2235,1,42,118,247,3,0,False
2236,1,0,0,8,2,0,True
2237,0,32,12,24,3,0,False
2238,1,80,30,61,5,0,False
2239,1,2,1,21,1,1,True

In [26]:
new_df.isnull().sum()

Teenhome               0
MntFishProducts        0
MntSweetProducts       0
MntGoldProds           0
NumCatalogPurchases    0
Response               0
Education_PhD          0
dtype: int64

In [27]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(new_df)

In [ ]:
wcss = []

for i in range(1, 11):
    kmeans = Kmeans(n_clue)